# Generated by Django 6.0.3 on 2026-03-27 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, verbose_name='Описание жанра')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название студии/компании')),
                ('year_foundation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Год основания')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна расположения')),
                ('director', models.CharField(blank=True, max_length=150, null=True, verbose_name='Глава компании')),
                ('website', models.URLField(blank=True, max_length=300, null=True, verbose_name='Сайт компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studios_logos/', verbose_name='Логотип компании')),
            ],
            options={
                'verbose_name': 'Студия-разработчик',
                'verbose_name_plural': 'Студии-разработчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название платформы')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Производитель')),
                ('release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2026)], verbose_name='Год выпуска платформы')),
                ('description', models.TextField(blank=True, verbose_name='Описание платформы')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры')),
                ('release_date', models.DateField(blank=True, help_text='Дата первого релиза игры', null=True, verbose_name='Дата выхода')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание игры')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='game_covers/', verbose_name='Обложка игры')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена в рублях', max_digits=10, null=True, verbose_name='Цена')),
                ('video_review_url', models.URLField(blank=True, help_text='Ссылка на YouTube видео с обзором', max_length=500, null=True, verbose_name='Ссылка на видео-обзор')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для покупки')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('categories', models.ManyToManyField(blank=True, related_name='games', to='games.category', verbose_name='Жанры')),
                ('game_studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.gamestudio', verbose_name='Студия-разработчик')),
                ('platforms', models.ManyToManyField(blank=True, related_name='games', to='games.platform', verbose_name='Платформы')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-release_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='Оценка от 1 до 10 (можно оставить отзыв без оценки)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('comment', models.TextField(max_length=5000, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
