# Generated by Django 6.0.3 on 2026-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, help_text='Загрузите файл игры', null=True, upload_to='game_files/', verbose_name='Файл игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_review_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео с обзором', max_length=500, null=True, verbose_name='Ссылка на видео-обзор'),
        ),
    ]
