# Generated by Django 6.0.3 on 2026-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_file_alter_game_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_image',
            field=models.ImageField(blank=True, null=True, upload_to='platform_image/', verbose_name='Картинка устройства'),
        ),
    ]
