# Generated by Django 6.0.3 on 2026-04-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_platform_platform_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='has_rating',
            field=models.BooleanField(default=False, verbose_name='Есть оценка'),
        ),
    ]
